# before_script:
#   - apt update && apt install -y cmake python-pip python-dev
#   - pip install conan
#   - export CONAN_USER_HOME=$(pwd)
#   - conan user
#   - conan remote add cpp-russia-ci http://cpp-russia-ci3.filonovpv.name:9300

stages:
  - build
  - deploy


build:gcc-5:
  stage: build
  image: gcc:5
  script:
    - mkdir build && cd build
    # - conan install --build=missing ..
    # - cmake ..
    # - make
    - mkdir bin
    - echo 'echo "Hello"' >> bin/wello
    - chmod 755 bin/wello
  tags:
    - docker
  artifacts:
    paths:
      - build/bin/

deploy:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN cpp-russia-ci3.filonovpv.name:5000
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  dependencies:
    - build:gcc-5
