before_script:
  - apt update && apt install -y cmake python-pip python-dev
  - pip install conan
  - export CONAN_USER_HOME=$(pwd)
  - conan user
  - conan remote add cpp-russia-ci http://cpp-russia-ci3.filonovpv.name:9300

stages:
  - build
  - deploy


build:gcc-4:
  stage: build
  image: gcc:4
  script:
    - mkdir build && cd build
    - conan install --build=missing -s compiler=gcc -s compiler.libcxx=libstdc++11 ..
    - cmake ..
    - make
  tags:
    - docker
  artifacts:
    paths:
      - build/bin/

deploy:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN cpp-russia-ci3.filonovpv.name:5005
  script:
    - docker build -t cpp-russia-ci3.filonovpv.name:5005/cpp-russia/wello .
    - docker push cpp-russia-ci3.filonovpv.name:5005/cpp-russia/wello
  dependencies:
    - build:gcc-4
